ads/ads/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('advertisement.urls')),
]

ads/advertisement/urls.py
from django.urls import path
from .views import AdsCreate, AdsList, AdsDetail


urlpatterns = [
   path('', AdsList.as_view()),

   path('ads/', AdsList.as_view(), name='news_list'),
   path('ads/<int:pk>', AdsDetail.as_view(), name='a_ads'),

   path('ads/create/', AdsCreate.as_view(), name='ads_create'),
   # path('news/<int:pk>/edit/', NewsEdit.as_view(), name='post_edit'),
   # path('news/<int:pk>/delete/', NewsDelete.as_view(), name='post_delete')
]

ads/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, TemplateView
from .views import BaseRegisterView, PersonalClassView, upgrade_me


urlpatterns = [
    path('login/', LoginView.as_view(template_name='sign/login.html'), name='login'),
    path('logout_confirm/', TemplateView.as_view(template_name='sign/logout_confirm.html'), name='logout_confirm'),
    path('logout/', LogoutView.as_view(template_name='sign/logout.html'), name='logout'),
    path('signup/', BaseRegisterView.as_view(template_name='sign/signup.html'), name='signup'),
    path('personal_acc/', PersonalClassView.as_view(template_name='sign/personal_acc.html'), name='personal_acc'),
    path('personal_acc/upgrade/', upgrade_me, name='upgrade')
]

ads/advertisement/models.py
from django.contrib.auth.models import User
from django.db import models
from tinymce.models import HTMLField


# class Author(models.Model):
#     user = models.OneToOneField(User, on_delete=models.PROTECT, verbose_name='Имя')
#
#     def __str__(self):
#         return f'{self.user}'


class Ads(models.Model):
    title = models.CharField(max_length=100, default='Без названия', verbose_name='Заголовок')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    # content = models.CharField(max_length=2500, default='default content', verbose_name='Контент')
    content = HTMLField(max_length=2500, default=False, verbose_name='Контент')

    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категории')

    responses = models.ManyToManyField('User', through='Response', verbose_name='Категории')

    def __str__(self):
        return f'{self.title}: {self.content[:50]}'


class Category(models.Model):
    name = models.CharField(max_length=50, default=False, verbose_name='Заголовок')

    def __str__(self):
        return f'{self.name}'


class Response(models.Model):
    ads = models.ForeignKey(Ads, on_delete=models.CASCADE, verbose_name='Автор')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор отклика')

ads/sign/models.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group
from django import forms
# from allauth.account.forms import SignupForm


class BaseRegisterForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    first_name = forms.CharField(label="Имя")
    last_name = forms.CharField(label="Фамилия")

    class Meta:
        model = User
        fields = ("username",
                  "first_name",
                  "last_name",
                  "email",
                  "password1",
                  "password2", )


# class BasicSignupForm(SignupForm):
#
#     def save(self, request):
#         user = super(BasicSignupForm, self).save(request)
#         basic_group = Group.objects.get(name='common')
#         basic_group.user_set.add(user)
#         return user

ads/advertisement/forms.py
from django import forms
from .models import Ads


class AdsForm(forms.ModelForm):
    class Meta:
        model = Ads
        fields = ['title', 'content', 'category']
        widgets = {
            'time_create': forms.DateInput(attrs={'type': 'date'}),
        }

ads/advertisement/views.py
import datetime
from datetime import date
import logging

from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from .models import Ads, Category, Response
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy

from .forms import AdsForm


class AdsList(ListView):
    model = Ads
    ordering = 'time_create'

    # queryset = Post.objects.order_by('time_create')

    template_name = 'ads_list.html'
    context_object_name = 'Ads'
    paginate_by = 5

    def get_queryset(self):
        # self.category = get_object_or_404(Category, id=self.kwargs['pk'])
        queryset = Ads.objects.order_by('-time_create')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_authors'] = not self.request.user.groups.filter(name='authors').exists()
        # context['category'] = self.category

        return context


class AdsDetail(DetailView):
    model = Ads
    template_name = 'a_ads.html'
    context_object_name = 'A_ads'

    def get_object(self, *args, **kwargs):
        obj = super().get_object(queryset=self.queryset)
        return obj


class AdsCreate(CreateView): #(PermissionRequiredMixin, CreateView):
    permission_required = ('ads.add_ads',)
    form_class = AdsForm
    model = Ads
    template_name = 'ads_edit.html'
    success_url = reverse_lazy('ads_list')

    def form_valid(self, form):
        # form.instance.write_type = 'NE'
        ads = form.save(commit=False)
        ads.author = self.request.user.author

        user_id = self.request.user.id
        # author_id = Author.objects.get(user=user_id)
        date_create = date.today()
        date_list = [dt.strftime("%Y-%m-%d") for dt in Ads.objects.filter(author=user_id).values_list('time_create', flat=True)]
        print(f'ads = {ads}, user_id = {user_id}, date_create = {date_create}, date_list = {date_list}')
        if date_list.count(date_create) <= 15:
            print(f'Публикаций пользователя {self.request.user} за сегодня - {date_list.count(date_create)} шт.')
            ads.save()
            print('Пост сохранен')
            # new_post.delay(post.pk)
            return super().form_valid(form)
        else:
            print('Пост не сохранен')
            print(self.get_context_data(form=form))
            # return redirect('/to_many_post/')


class NewsEdit(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    permission_required = ('ads.change_ads',)
    form_class = AdsForm
    model = Ads
    template_name = 'ads_edit.html'
    success_url = reverse_lazy('ads_list')

ads/sign/views.py
from django.contrib.auth.models import User, Group
from django.views.generic.edit import CreateView
from .models import BaseRegisterForm
# from ads.advertisement.models import Author
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import TemplateView
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required


class BaseRegisterView(CreateView):
    model = User
    form_class = BaseRegisterForm
    success_url = '/ '


class PersonalClassView(LoginRequiredMixin, TemplateView):
    template_name = 'protect/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(f"self.request = {self.request.user.id}")
        # context['is_not_subscriber'] = self.request.user not in self.category.subscribers.all()
        # context['category'] = self.category
        return context


@login_required
def upgrade_me(request):
    user = request.user
    premium_group = Group.objects.get(name='authors')
    if not request.user.groups.filter(name='authors').exists():
        premium_group.user_set.add(user)
        Author.objects.create(user=user)
    return redirect('to_many_post')

ads/templates/a_ads.html
{% extends 'flatpages/default.html' %}

<!--{% load custom_filters %}-->

{% block title %}
Объявление
{% endblock title %}

<!-- В контенте на странице мы выводим пост -->
{% block content %}
<h1>Объявление</h1>

<h4>{{ A_ads.title }}</h4>
{% for category in A_ads.category.all %}
    <a href="{% url 'category_list' ads.id %}" style="...">"{{ category }}"</a>
{% endfor %}
<h6>{{ A_ads.time_create|date:'d M Y' }}</h6>
<br>{{ A_ads.content}}

{% endblock content %}

ads/templates/ads_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Объявление</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

ads/templates/ads_list.html
{% extends 'flatpages/default.html' %}

{% block title %}
Объявления
{% endblock title %}

{% block content %}
    <h1>Все объявления</h1>
    <h3>Объявлений на странице: {{ Ads|length }}</h3>
    <hr>
    {% if Ads %}
        <!-- Для каждого объявления будет генерироваться новая строчка -->
        {% for a_ads in Ads %}
            <!-- Здесь можно получать доступ к полям объекта модели. -->
            <h5><a href="http://127.0.0.1:8000/ads/{{ a_ads.id }}">{{ ads.title }}</a></h5>
            <h6>{% for category in ads.category.all %}
                    <a href="{% url 'category_list' category.id %}" style="...">"{{ category }}"</a>
                {% endfor %}</h6>
            {{ ads.time_create|date:'d M Y' }}
            {{ ads.content|truncatewords:20 }}
        {% endfor %}
        <br>
    {% else %}
        <h2>Объявлений пока нет!</h2>
    {% endif %}

<!-- Добавляем пагинацию на страницу-->
    {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
        {% endif %}

<!--{# Информация о текущей странице #}-->
    {{ page_obj.number }}

<!--{# Информация о следующих страницах #}-->
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}